### ISSUE TITLE
Support tables

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#11]
- [x] Add a semicolon to the end of each cell except the last.
- [x] Start a new row on a new line.
- [x] Negatively indent the first line of a row if it spans multiple braille lines.
- [x] Replace empty cells with "gg".
- [x] Insert "bt" before the table, insert "et" after the table.

**Comment by bertfrees** [comment]
> Replace empty cells with "gg".

Currently this can only be done by adding "gg" with your XSLT. I've thought about adding a pseudo-class `:blank` as well, but using XSLT for now seems easier for now.

Note that what you have described here is not the same as what we call "matrix tables" in other places.

**Comment by dkager** [comment]
OK, let's just call them tables. :)
Another option could be to have fallback content, like `td { content: fallback('gg'); }`

**Comment by dkager** [comment]
Also of interest:
https://www.w3.org/TR/css3-selectors/#empty-pseudo

**Comment by bertfrees** [comment]
OK `:empty` seems to be supported already :) Nice. Forget about `:blank` then.

**Comment by dkager** [comment]
Closing unless review shows up something bad.
