### ISSUE TITLE
Fix transform query not fully recognized

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#15]
I'm not sure what's up. From the dp2 CLI:

```
(1)[ERROR]      java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(formatter:dotify)(translator:dedicon)(locale:nl)
```

**Comment by dkager** [comment]
The problem appears to be that liblouis can't resolve or compile the tables.

**Comment by bertfrees** [comment]
See https://github.com/snaekobbi/pipeline-mod-dedicon/commit/ef2d06cc3dc7c8ba5ea6a493f4cc9de1052b5a9a
