### ISSUE TITLE
Generate title pages

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#16]
- [x] For prod:docType "ro".
- [x] For prod:docType "sv".

**Comment by dkager** [comment]
Anticipating the next round of product specifications, the date can most likely be removed from the title page. So converting month names to Dutch isn't required just yet.

**Comment by dkager** [comment]
The problem is that <docauthor> is optional. @bertfrees, is there a recommended way in XSLT to match the last element out of two? E.g. insert the title page after the last docauthor, but if there are none then insert after the last doctitle.
On a similar note, the XSLT should probably insert an empty <rearmatter> if none exists before trying to put a colophon in it.

**Comment by stesk** [comment]
@dkager Try something like `frontmatter/(doctitle|docauthor)[last()]`. If it's possible to have neither `<doctitle>` nor `<docauthor>`, then you have to match `frontmatter[not(doctitle|docauthor)]` and insert the elements there.

**Comment by dkager** [comment]
Thanks. I tried something like that but it didn't quite work. Probably because I got the parentheses wrong. I'll try again!
As for the absence of both elements: I'm considering pre-adding them so I have a somewhat predictable basis to work from. But that's still open for debate as I don't know how fault-tolerant I need to make the script.

**Comment by dkager** [comment]
This is the culprit:

```
Static error at char 13 in {frontmatter/(doctitle} in pattern in xsl:template/@match on line 10 column 66 of generate-boilerplate.xsl:
XTSE0340: Parentheses are not allowed in an XSLT 2.0 pattern
```

**Comment by stesk** [comment]
@dkager Yeah, I forgot that you can't use parentheses when matching. So this should do it: `frontmatter/*[self::doctitle or self::docauthor][last()]`. Not exactly elegant, but it's what comes to mind.

**Comment by dkager** [comment]
Clever. My XPath skills need work. ☺

**Comment by dkager** [comment]
Done (barring future changes to the specifications).
