### ISSUE TITLE
Make unit tests work on Windows

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#17]
So that Davy can run `mvn test` every time before he commits.

**Comment by dkager** [comment]
The problem is that you cannot pass null to mavenBundlesWithDependencies, as is being done for libhyphen-native on Windows.

**Comment by bertfrees** [comment]
Yes, I have to fix that. But is that really the issue? Because I just recently changed to pax-exam-helper 2.0.0. Could you try running the tests with that line removed?

**Comment by dkager** [comment]
I just did: the CSS tests fail but at least they run.

**Comment by dkager** [comment]
Patch:

```
--- a/pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java
+++ b/pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java
@@ -327,6 +327,7 @@ public abstract class Options {
        private MavenBundlesWithDependencies(MavenBundleOption... options) {
            fromBundles = new ArrayList<MavenBundle>();
            for (MavenBundleOption o : options)
+               if (o == null) continue;
                for (MavenBundle b : o.getBundles())
                    fromBundles.add(b);
            logger.info(this.toString());
```

**Comment by dkager** [comment]
JVM option `file.encoding=UTF8` is also needed. See #24.

**Comment by bertfrees** [comment]
I'll add the system property to the test.

**Comment by bertfrees** [comment]
@dkager Now that the libhyphen-native line is commented out, the system property is added, and the pax-exam-helper fix is underway, could you start running `mvn test` every once in a while? Now I have to fix the tests which is not ideal because I don't really know what is expected. Also, there are some pending tests with TODO items (mostly about verifying expected result), I'd appreciate it if you could have a look at those so that we can enable as much tests as possible.

**Comment by dkager** [comment]
This will become much easier when we can switch from PEF and/or default ascii-table to BRF with the Dutch Braillo table.

**Comment by dkager** [comment]
What is the status of the pax-exam fix? It seemed pretty trivial.

**Comment by bertfrees** [comment]
Fix is incorporated but haven't released a new version yet. But I'm going to add support for libhyphen on Windows so that this hack can be removed altogether.

**Comment by dkager** [comment]
I’d like to think of it as a useful addition, if someone wants to (temporarily) disable a module. :)

**Comment by bertfrees** [comment]
Sure. I'm not going to ditch it.

**Comment by dkager** [comment]
They work on Windows.
