### ISSUE TITLE
Add option to disable generating boilerplate

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#18]
To facilitate unit testing.

**Comment by bertfrees** [comment]
Something you need from me?

**Comment by dkager** [comment]
@bertfrees Do you think we could/should make this a generic option? Both to make unit tests shorter and for customized productions where you don't want the usual boilerplate. Or maybe people want different boilerplates they can choose and save in a template?

**Comment by bertfrees** [comment]
It definitely sounds like a good option to have, but I don't really see how we can make this a generic option at the moment. I would simply start by adding the option to the Dedicon script and if we see an opportunity later to make it generic, sure. Let me try something...

**Comment by bertfrees** [comment]
Can be closed?
