### ISSUE TITLE
Investigate blank page after generated content and TOC

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#19]
This is the first page of the proper volume, after the flows. Why is it empty?

**Comment by bertfrees** [comment]
This is because of a recent change I did. I think for now it's best to remove page-break-after from the last section.

**Comment by dkager** [comment]
The last section being the last level in frontmatter?

**Comment by bertfrees** [comment]
Yes, that's what I meant.

**Comment by bertfrees** [comment]
Disabled `page-break-after` in your CSS for now: https://github.com/snaekobbi/pipeline-mod-dedicon/blob/03b629770b1a45d72c6d1a150dc69192118ca3e3/src/main/resources/css/dedicon-default.css#L111. `page-break-before` should be enough.

**Comment by dkager** [comment]
This does not fix the problem, in fact now I have two blank pages after the TOC and none between titlepage and TOC.

**Comment by dkager** [comment]
By the way, the print page number in header and the rendering of pagenums as block elements is also still broken. Is it clear what the problems are or should I open some specific issues? This will come into play at the time of acceptance testing.

**Comment by bertfrees** [comment]
Yes it is clear what the problem with the print page number is. This is actually one of the next things I'm going to address.

Regarding why there was is no page break between the title page and the TOC: that is because the TOC doesn't have a page-break-before.

My solution of removing page-break-after indeed didn't fix your problem. That's because I hadn't understood the issue properly. It would be great if there was a unit test for the issue.

Speaking of unit tests: could you have a look at the ones that have TODO's?

**Comment by dkager** [comment]
Can I already run unit tests? #17

**Comment by bertfrees** [comment]
The real problem appears to be the empty frontmatter (the doctitle is not rendered). The frontmatter has `page-break-after: always`and the bodymatter that comes after the frontmatter has `page-break-before: always`, so the empty box generated by the empty frontmatter causes an empty page. The [specification](http://snaekobbi.github.io/braille-css-spec/master/index.html#h4_page-breaking-rules) isn't totally clear about this case but I think the current behavior is correct. The following CSS fixes it (after you've also un-reverted my previous change):

``` css
frontmatter:not(:has(> *:not(doctitle, docauthor, #generated-title-page))) {
   display: none;
}
```

**Comment by bertfrees** [comment]
Oh, and when you've un-reverted my `page-break-after` removal, you can add a page break before the TOC with the following rule:

``` css
 #generated-volume-toc::-obfl-on-toc-start {
    page-break-before: always;
}
```

**Comment by dkager** [comment]
There is also a blank page after the rearmatter. Same issue?

**Comment by dkager** [comment]
> `frontmatter:not(:has(> *:not(doctitle, docauthor, #generated-title-page)))`

This doesn't seem to match the element (or my more generic frontmatter { display: block; } wins out).

**Comment by dkager** [comment]
Should be fixed.
