### ISSUE TITLE
Handle inline superscript and subscript

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#2]
In the following translation the number sign (⠼) is placed incorrectly.

XML:
`<p><em>Geestelijk leven is niet mogelijk zonder te leren.<sup>1</sup></em></p>`

PEF:
⠨⠛⠑⠑⠎⠞⠑⠇⠊⠚⠅⠀⠇⠑⠧⠑⠝⠀⠊⠎⠀⠝⠊⠑⠞⠀⠍⠕⠛⠑⠇⠊⠚⠅
⠵⠕⠝⠙⠑⠗⠀⠞⠑⠀⠇⠑⠗⠑⠝⠼⠲⠁

The correct notation is to place the number sign one position to the right.

The likely cause is that paragraphs including inline elements are translated as a whole. This particular case, a period followed by a number, should be fixed in the current version of the Dutch tables. But even then, superscript and subscript should probably get handled differently to distinguish them from regular numbers. Needs some more investigation.

**Comment by bertfrees** [comment]
@dkager If this can be fixed by updating the liblouis table (without a dependency on liblouis 3.0), and if the priority is high enough to fix in this sprint, go for it!

**Comment by dkager** [comment]
I already updated the tables in master. There’s also an initial shot at a default CSS. This needs more tweaking, but it would be nice if we can release v1.1.0 of mod-dedicon along with the next mod-braille.

**Comment by bertfrees** [comment]
Oh, OK. Changes look pretty good, also the CSS. Is this issue #2 fixed by commit 2de6bd57edc928fd0c6fcb8f3eb9fef1bc38b1bd?

**Comment by dkager** [comment]
Can I easily test the new tables with the current system? Testing with just liblouis looks good.

**Comment by dkager** [comment]
One more question: can one add arbitrary braille dots to the start or end of an element’s content using Braille CSS? It looks like this would be enough to get superscript and subscript to behave as expected.

**Comment by bertfrees** [comment]
OK.

Sure you can easily test within the current system. Just use the JUnit/xspec/xprocspec tests. Liblouis harness tests are not supported though. But I was thinking more specifically the `<p><em>Geestelijk leven is niet mogelijk zonder te leren.<sup>1</sup></em></p>` case which you can't test in a harness test anyway (although in this case the result will be exactly the same because not much special is going on in the XSLT yet.) Also we're not using the default table from liblouis (you've copied it for now) so any bugs related to that can be spotted with a test in this module.

Anyway, if you feel confident enough it is fixed it's fine.

What kind of specific processing did you plan on "sub" and "sup" elements?

**Comment by bertfrees** [comment]
> can one add arbitrary braille dots to the start or end of an element’s content using Braille CSS?

You can with for example:

``` css
sup::before {
  content: '^'
}
sub::before {
  content: '_'
}
```

**Comment by bertfrees** [comment]
Note that the way things are implemented now, the "^" and "_" would be translated separately, and "... zonder te leren.1" would still be translated as a whole, without the generated content inserted yet. We can of course change that if needed.

**Comment by dkager** [comment]
> Note that the way things are implemented now, the "^" and "_" would be translated separately

That sounds like a problem. Maybe there should be an option to translate inline elements separately? I’m afraid this may cause too much overhead, but who knows. To be continued on Monday.

**Comment by dkager** [comment]
@bertfrees Could we do something like in 661556bf90bc30b059365fd6386434568c460dbf?

**Comment by bertfrees** [comment]
Yes that'll work. You'll have to move it to the "text" variable. Something like:

``` xsl
<xsl:variable name="text" as="xs:string*">
  <xsl:for-each select="//text()">
    <xsl:sequence select="if (ancestor::sup) then concat('^',.)
                          else if (ancestor::sub) then concat('_',.)
                          else ."/>
  </xsl:for-each>
</xsl:variable/>
<xsl:variable name="style" as="xs:string*">
  <xsl:for-each select="//text()">
    ...
```

**Comment by dkager** [comment]
In 0faa662. Enough reason to release an update for the module iMO.
Not yet tested as I don't see a straight-forward way to do that locally.

**Comment by bertfrees** [comment]
OK. I'll add a basic test and release.

**Comment by bertfrees** [comment]
@dkager I have pushed a branch called [fix_build](https://github.com/snaekobbi/pipeline-mod-dedicon/tree/fix_build) which adds a test and a fix. It also fixes the liblouis table which was not compatible with liblouis < 3.0.0 anymore after your additions.

**Comment by dkager** [comment]
Thanks! I have merged these changes into master (aren't we at pipeline-mod-braille 1.9.5?).

**Comment by bertfrees** [comment]
1.9.5 was released yesterday. mod-dedicon is for next time unfortunately.

**Comment by dkager** [comment]
Ah my bad, I checked the POM in master. ☺
