### ISSUE TITLE
Generate colophons

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#22]
This should be the last content in the book (not the volume). Based on `prod:docType` and `prod:colophon`, re #6.

**Comment by dkager** [comment]
The XSLT works when ran with Saxon-HE, but the output isn't shown in Pipeline conversions. Needs some more work.

**Comment by dkager** [comment]
the problem is that my XSLT doesn't match empty rearmatter if the element contains whitespace, e.g.:

```
<rearmatter>
</rearmatter>
```

**Comment by bertfrees** [comment]
Yeah, your XSLT is a bit unconventional. It's more common to do it like this:

``` xml
<xsl:template match="rearmatter">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
      <xsl:call-template name="generate-colophon-page"/> 
    </xsl:copy>
  </xsl:template>
```

**Comment by dkager** [comment]
Speaking of that, why does the identity template match against node(), not node()|@\* ?

**Comment by bertfrees** [comment]
Dunno, you wrote that :) But you don't need any templates that match `@*` if there are no `<xsl:apply-templates select="@*"/>`. You always do `<xsl:copy-of select="@*"/>` so it's fine.

**Comment by bertfrees** [comment]
So my snippet should become:

``` xml
<xsl:template match="rearmatter">
  <xsl:copy>
    <xsl:sequence select="@*"/>
    <xsl:apply-templates/>
    <xsl:call-template name="generate-colophon-page"/> 
  </xsl:copy>
</xsl:template>
```

**Comment by dkager** [comment]
Done.
