### ISSUE TITLE
Make all options work

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#23]
- Options that have been implemented in the generic dtbook-to-pef should not be overwritten.
- Options that were not generic enough to implement in the generic dtbook-to-pef should be implemented here.

I have fixed `$page-width`, `$page-height`, `$show-braille-page-numbers` and `$show-print-page-numbers` in https://github.com/snaekobbi/pipeline-mod-dedicon/commit/a771a4878a42d17addfc67e4a6ef04c0e0a1ed68. But there might be other options left. Ideally all options, especially the ones implemented here, should be covered by unit tests.

**Comment by dkager** [comment]
First step is probably to remove unused options. But right now, with acceptance testing around the corner, I’m much more concerned about getting output as per the specs. We’re still a way off there.

**Comment by dkager** [comment]
I propose we remove (in xml-to-pef):
- [x] ignore-document-title
- [x] include-symbols-list
- [x] choice-of-colophon

**Comment by dkager** [comment]
All options now have sensible default values. Unimplemented options are removed.
