### ISSUE TITLE
Look into failing inline CSS step

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#24]
Using pipeline-mod-braille:1.9.10 (on Windows) `mvn test` fails:

```
...
[INFO] Inlining CSS
[ERROR] cz.vutbr.web.css.CSSException: Unable to parse URL CSS style
...
```

**Comment by bertfrees** [comment]
See also https://github.com/daisy/pipeline-mod-braille/commit/d9adda521828272ce9e50168424a146ebaec262d

**Comment by dkager** [comment]
Is there still something to do for this issue?

**Comment by bertfrees** [comment]
I guess to fix the issue properly, not by using the "workaround".

**Comment by dkager** [comment]
For now, setting environment variable `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` will fix this.
