### ISSUE TITLE
Define page-width/-height and maximum-number-of-sheets based on metadata field

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#26]
This again depends on prod:docType. Probably easiest to implement with a fixed list of values. The prettiest solution would be to have two values:
1. From metadata field.
2. Custom integer.

Especially for maximum-number-of-pages this would be ideal.

**Comment by bertfrees** [comment]
Tricky. That would mean hybrid data types and new special widgets. Maybe easier is to have a special integer value (also the default value) that represents the metadata field, e.g. '0' or a negative numbers.

**Comment by dkager** [comment]
Either that, or a list as I said. For page-width/-height that would work, you end up with about 20 values.
But ‘enter -1 for the default’ is also a good option.
