### ISSUE TITLE
Add option $show-inline-print-page-numbers

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#30]
By inline I mean requirement 4.8:105. This is necessary because some output formats (AL) require the print page number to be shown at the top of the page, but not inline. Is this useful for the generic script?

**Comment by bertfrees** [comment]
I'm going to start with adapting your script so that it is easy to add new options and pass them as parameters and SASS variables. Later we can still decide to move options to the generic script if they are useful.
