### ISSUE TITLE
Support notes

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#31]
- [x] Noterefs are indicated by an asterisk.
- [x] The entire text of the note is indented 2 cells.
- [x] Notes are indicated by an asterisk immediately before the text, i.e. indented 1 cell.
- [x] There is a blank line before and after the note.

**Comment by dkager** [comment]
TODO: if notes are stored elsewhere than the noteref, move them to the right (inline) place.
@bertfrees: You suggested doing this with XSLT. Something similar is done with the doctitle and docauthor, except these are left in the XML and duplicated on the generated title page. Here I'm thinking of actually moving the notes to the right place.

**Comment by bertfrees** [comment]
I don't recall. But if you mean that a note should be inserted inline at the position of the noteref, you can do this with CSS. Something like:

``` css
noteref::after {
  content: target-content(attr(idref url));
}
```

**Comment by dkager** [comment]
I was trying out block-translate.xsl, but `//` seems to match the active `css:block`? The notes live outside the active block.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-mod-braille/issues/106
