### ISSUE TITLE
dev-launcher fails with dedicon:dtbook-to-pef

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#38]
Using latest master, this is back again:

```
Job 51526651-dd9b-4cd8-a5a0-f33d5514b739 sent to the server
(1)[INFO]       Generating table of contents
(2)[INFO]       Inlining CSS
(3)[INFO]       Transforming MathML
(4)[INFO]       Transforming from XML with inline CSS to PEF
(5)[ERROR]      java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(formatter:dotify)(translator:dedicon)(locale:nl)
(6)[ERROR]      java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(formatter:dotify)(translator:dedicon)(locale:nl)
```

**Comment by dkager** [comment]
Presumably happened when I switched to the latest mod-braille.

Additional info:

```
WARN   [o.d.p.b.tex.impl.TexHyphenatorDotifyImpl] A query with 'libhyphen-table' never matches anything   @o.d.p.b.t.i.TexHyphenatorDotifyImpl:114#_get
WARN   [o.d.p.b.tex.impl.TexHyphenatorSimpleImpl] A query with 'libhyphen-table' never matches anything   @o.d.p.b.t.i.TexHyphenatorSimpleImpl:107#_get
```

**Comment by dkager** [comment]
The same thing happens with the generic dtbook-to-pef script and latest pipeline-assembly master (pointing to pipeline-mod-braille 1.9.13-SNAPSHOT).

**Comment by bertfrees** [comment]
This is a snapshots problems again. You should depend on the "file-format" branch of pipeline-mod-braille. "master" contains some backwards-incompatible changes.

**Comment by bertfrees** [comment]
One of the things we discusses in the Pipeline face-to-face meeting was to create "aggregator projects" (repos that include the source code of several sub-repos) which should make it easier to branch several repos at once and to always make sure you are building against the right dependencies.

See https://github.com/daisy/pipeline-tasks/issues/34

**Comment by dkager** [comment]
File-format branch had the same issue, but no apparent cause in the logs. 1.9.12 is also affected as far as I can tell.

**Comment by bertfrees** [comment]
To make sure that this isn't a snapshot issue, try with [assembly 1.9.13](https://github.com/daisy/pipeline-assembly/tree/release/1.9.13) and [latest mod-dedicon](https://github.com/snaekobbi/pipeline-mod-dedicon/commit/3933253e7a9bf7ee6db73d6ee67be4d3a39de873). If that still doesn't work, I need to investigate deeper.

**Comment by dkager** [comment]
On tag v1.9.13 of pipeline-assembly without having included pipeline-mod-dedicon I also get this error with dtbook-to-pef:

```
pipeline-assembly\target\cli\win32\dp2.exe dtbook-to-pef --i-source test.xml --output out --x-toc-depth 6 --x-page-width 33 --x-page-height 28 --x-include-brf true

Job c955878d-ff2f-4034-915e-4c8059674145 sent to the server
(1)[INFO]       Inlining CSS
(2)[INFO]       Transforming MathML
(3)[INFO]       Transforming from XML with inline CSS to PEF
(4)[ERROR]      java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(translator:lib
louis)(formatter:dotify)(locale:nl)
(5)[ERROR]      java.lang.RuntimeException: Could not find a Transform for query: (input:css)(output:pef)(translator:lib
louis)(formatter:dotify)(locale:nl)
```

**Comment by dkager** [comment]
Remember to remove mac/linux config files from target/dev-launcher/etc.
