### ISSUE TITLE
Table of contents in backmatter of last volume

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#40]
@dkager: is this indeed the requirement, or was it the _frontmatter_ of the last volume? I forgot.

**Comment by bertfrees** [comment]
It turns out that `toc-sequence` is not allowed inside `post-content`: http://braillespecs.github.io/obfl/obfl-specification.html#L9241.

**Comment by dkager** [comment]
I.e. this means updating the spec and the formatter if it is to be done at all?

**Comment by bertfrees** [comment]
Yeah.

**Comment by dkager** [comment]
We have discussed this internally and came up with the following alternative:
- The first volume contains the document-level TOC.
- All other volumes contain a volume-level TOC.
- All TOCs are placed at the beginning of the volume.

Is this implementable? As a bonus it avoids having to update the OBFL spec.

**Comment by bertfrees** [comment]
Yes, you can do that with CSS.

**Comment by bertfrees** [comment]
The only thing you can't currently do is to put a TOC at the end of a volume. We'd have to ask Joel to know how much work that would be. My guess is that it wouldn't be much work. But I think it's best to have a working temporary solution ASAP and then think about optimizing later.

**Comment by dkager** [comment]
Yes, I definitely want to ask about the feasibility of a TOC at the end of a volume. This is what our current specs call for. So even if the specs are somewhat flexible, we should try to follow them to guarantee acceptance testing goes well.

**Comment by bertfrees** [comment]
@dkager This can be implemented properly now.
