### ISSUE TITLE
Fix uncommon dot patterns in NL Braillo 650 table

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#44]
Looked good in unit tests but the hardware didn't print the 'ë'. Going to do a test print of all 64 dot patterns and correct the BRF table as needed.

**Comment by dkager** [comment]
Further inspection showed that our current converter outputs ANSI whereas braille-utils outputs UTF-8. Assuming this is the issue we'll want to convert to ANSI.

**Comment by dkager** [comment]
Looks like you can set the preferred charset in EmbosserBrailleConverter, but I'm not sure if that is supposed to affect the BRF file output.

**Comment by bertfrees** [comment]
The preferred charset is used in org.daisy.pipeline.braille.pef.impl.ConfigurableFileFormat. Either you change the table, or the alternative is that we make a feature for ConfigurableFileFormat that you can set to overwrite the preferred charset.

**Comment by dkager** [comment]
Another feature for the query sounds good.

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-mod-braille/issues/122

**Comment by dkager** [comment]
BTW I can't see how the class you mentioned uses the charset.

**Comment by bertfrees** [comment]
It's in the BRFWriter class.

**Comment by dkager** [comment]
Since we want the windows-1252 charset doing it in the table is probably a bad idea. Not very cross-platform. So I'll look at adding a feature to the FileFormat.
