### ISSUE TITLE
No auto hyphenation (on Windows)

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#45]
Using pipeline-mod-dedicon-1.6.1-SNAPSHOT and the default rules from dtbook-to-pef:

```
@if $hyphenation {
    :root {
        hyphens: auto;
    }
}
```

Q: does this work on Linux? In that case there may be something wrong with the Windows native library. If it goes wrong on Linux too then my 'from-meta' option probably has issues.

**Comment by bertfrees** [comment]
I don't know, if it has a unit test, then yes it works.

**Comment by dkager** [comment]
Hyphenation works on Linux (the test server). Something wrong with the Windows end I think.

**Comment by bertfrees** [comment]
You mean the dev-launcher?

**Comment by dkager** [comment]
Yes, but another potential cause is the from-meta not working due to a bug we fixed last week.

**Comment by bertfrees** [comment]
The dev-launcher was indeed missing the libhyphen-native-windows module, so that would explain why hyphenation fails. I've fixed that yesterday (last commit on the branch release/1.9.15).

**Comment by dkager** [comment]
> The dev-launcher was indeed missing the libhyphen-native-windows module, so that would explain why hyphenation fails. I've fixed that yesterday (last commit on the branch release/1.9.15).

That fixed it! :)

Could we also suppress these seemingly harmless messages, or make them debug level?

```
[INFO]      hyphens: auto could not be applied to target-counter(page)
```

**Comment by bertfrees** [comment]
Well, I would say for most of these warnings the same comment as for https://github.com/snaekobbi/pipeline-mod-dedicon/issues/29 applies: fix the CSS. But I guess we can drop the warnings for simple cases of counters (decimal) because hyphenation or preserving white space is never an issue in those cases.

**Comment by dkager** [comment]
Can the CSS even be fixed, short of not hyphenating the line containing the call to target-counter? That means not hyphenating TOC entries, which is a change in behavior.

**Comment by bertfrees** [comment]
It is possible when the line consists of multiple (pseudo-)elements (a trick that is also used [for example in mod-sbs to give the different segments different `text-transform`s](https://github.com/snaekobbi/pipeline-mod-sbs/blob/817efedb53f22f1b116676e8208ac1992b66d9c0/src/main/resources/css/default.scss#L176)), but it's maybe not so nice to do that only to avoid these warnings.

**Comment by bertfrees** [comment]
By the way I've even increased the level from INFO to WARN in a new version.

**Comment by dkager** [comment]
Worth a try though. I get about 30 of these on a small job.
