### ISSUE TITLE
Replace release notes on Github with links to NEWS file

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#47]
to solve problem of duplication described at http://www.mehdi-khalili.com/better-git-release-notes. I've already done this for the pipeline-mod-braille repository but the same can be done for pipeline-mod-nlb, pipeline-mod-celia, pipeline-mod-dedicon, pipeline-mod-mtm, pipeline-mod-sbs, pipeline-mod-nota and snaekobbi/system.

**Comment by dkager** [comment]
@bertfrees Sounds good. I don't think anything special needs to happen, right?

**Comment by bertfrees** [comment]
Just added this note to all repositories that currently have release notes on Github. You can ignore ("wontfix") it if you want. What I've done in pipeline-mod-braille is I've replaced the copy of the release notes on Github with links to the NEWS file.

**Comment by dkager** [comment]
Oh, I thought you meant just for _new_ releases.

**Comment by dkager** [comment]
Done.
