### ISSUE TITLE
NullPointerException when calling liblouis transform

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#48]
In DediconTranslator.java:140 the liblouis translator is called and throws a NPE:

```
return translator.transform(styledText);
```

Possible cause is daisy/pipeline-mod-braille@c818031.

**Comment by dkager** [comment]
Seems to have been fixed by updating to the latest dev-launcher (with libhyphen-native for Windows).

**Comment by bertfrees** [comment]
Ah, really? It must have been a hyphenator that was null. Will try to find what the problem was.
